### ISSUE TITLE
minimum example and necessary columns of data table?

### ISSUE THREAD

**Issue by hcji** [mathiaskalxdorf/RTSA#1]
Hi, 

Thanks for your great work!
I m trying to apply your package to my own dataset, but I m confused with the example data. There are so many information included in your example files. I wonder which of them are necessary for running your package. Furthermore, I find in your example config file, the temperture column includes 9 degree, but the header of the TMT related columns are TempX_conditionY_TMT_channel, where X is from 1-5, and Y is from 1-2. I think there are only five tempertures used? Am I right?
Could you please give a more detailed and clear example?

Best,
Ji

**Comment by mathiaskalxdorf** [comment]
Hey Ji,

I attached a more detailed explanation how the config file should be used. 
![Explanation](https://user-images.githubusercontent.com/43172587/119442741-aa64b400-bd28-11eb-88a9-2b7633937d2a.jpg)
For the example data set, in total 9 temperatures are covered, however, in a TMT10 setup with 2 conditions, only 5 can be covered per TMT-experiment. I hope the detailed explanation image can help. 
Regarding the columns in the example data, the RTSA analysis script was developed to be run on data preprocessed by an in-house analysis pipeline which by default reports many different columns. The majority is not required for the RTSA analysis run. Please quickly look through the RTSA code which of the columns are used.

Best,

Mathias
